<?php
#equations generated by WEKA machine learning linear regression classifier to detect drift
/*
    DOpct = 9.3 * Temp - 150.09 needs rebuilding
    Predicting 87.52 if attribute value is missing.
    Correlation coefficient             0.1249
    Mean absolute error                 56.178 
    Root mean squared error             103.5404
    Relative absolute error             99.1087 %
    Root relative squared error         99.2036 %
    Total Number of Instances           6411     
    Ignored Class Unknown Instances     478

    pH = -0.08 * Temp + 9
    Predicting 4.93 if attribute value is missing.
    Correlation coefficient             0.6442
    Mean absolute error                 0.3295
    Root mean squared error             0.475 
    Relative absolute error             69.3237 %
    Root relative squared error         76.4896 %
    Total Number of Instances           11595     
    Ignored Class Unknown Instances     1
*/
$drift_variables = [
    "temp"=> [
        "coeff"=>NULL,
        "x"=>NULL,
        "yi"=>NULL,
        "miss"=>NULL,
        "mae"=>NULL
    ],
    "ph"=> [
        "coeff"=>-0.08,
        "x"=>"temp",
        "yi"=>9,
        "miss"=>4.93,
        "mae"=>0.3295
    ],
    "phmv"=> [
        "coeff"=>NULL,
        "x"=>NULL,
        "yi"=>NULL,
        "miss"=>NULL,
        "mae"=>NULL
    ],
    "cond"=> [
        "coeff"=>NULL,
        "x"=>NULL,
        "yi"=>NULL,
        "miss"=>NULL,
        "mae"=>NULL
    ],
    "dopct" => [
        "coeff"=>9.3,
        "x"=>"temp",
        "yi"=>-150.09,
        "miss"=>87.52,
        "mae"=>56.178
    ],
    "domgl"=> [
        "coeff"=>NULL,
        "x"=>NULL,
        "yi"=>NULL,
        "miss"=>NULL,
        "mae"=>NULL
    ],
    "dogain"=> [
        "coeff"=>NULL,
        "x"=>NULL,
        "yi"=>NULL,
        "miss"=>NULL,
        "mae"=>NULL
    ],
    "turb"=> [
        "coeff"=>NULL,
        "x"=>NULL,
        "yi"=>NULL,
        "miss"=>NULL,
        "mae"=>NULL
    ],
    "depth"=> [
        "coeff"=>NULL,
        "x"=>NULL,
        "yi"=>NULL,
        "miss"=>NULL,
        "mae"=>NULL
    ]    
];
?>