<?php
#equations generated by WEKA machine learning linear regression classifier to detect drift
/*
currently temp/domgl represents a reciprocal audit, this should be fixed when temp is audited on the indepented temp sensor

    Temp = -1.22 * DOmgl + 26.66
    Predicting 22.51 if attribute value is missing.
    Correlation coefficient                  0.7167
    Mean absolute error                      2.6119
    Root mean squared error                  3.372 
    Relative absolute error                  64.8949 %
    Root relative squared error              69.7304 %
    Total Number of Instances                11591     
    Ignored Class Unknown Instances          5

    pH = 0.13 * DOmgl + 6.69
    Predicting 6.89 if attribute value is missing.
    Correlation coefficient                  0.6671
    Mean absolute error                      0.3198
    Root mean squared error                  0.4626
    Relative absolute error                  67.2918 %
    Root relative squared error              74.4885 %
    Total Number of Instances                11595     
    Ignored Class Unknown Instances          1 

    pHmv = -3.28 * Temp + 30.73
    Predicting -68.55 if attribute value is missing.
    Correlation coefficient                  0.5081
    Mean absolute error                      22.5244
    Root mean squared error                  26.7734
    Relative absolute error                  86.0909 %
    Root relative squared error              86.1213 %
    Total Number of Instances                11595     
    Ignored Class Unknown Instances          1 

    Cond = 0.01 * DOmgl + 0.7
    Predicting 1.03 if attribute value is missing.
    Correlation coefficient                  0.5248
    Mean absolute error                      0.1408
    Root mean squared error                  0.1807
    Relative absolute error                  83.4555 %
    Root relative squared error              85.1176 %
    Total Number of Instances                11586
    Ignored Class Unknown Instances          10

    DOpct = 28.54 * pH - 150.64
    Predicting 92 if attribute value is missing.
    Correlation coefficient                  0.5902
    Mean absolute error                      16.6455
    Root mean squared error                  21.7414
    Relative absolute error                  71.1853 %
    Root relative squared error              80.7153 %
    Total Number of Instances                8870     
    Ignored Class Unknown Instances          2726

    DOmgl = -0.41 * Temp + 13.85
    Predicting 6.8 if attribute value is missing.
    Correlation coefficient                  0.7047
    Mean absolute error                      1.6658
    Root mean squared error                  2.1121
    Relative absolute error                  64.8025 %
    Root relative squared error              70.9461 %
    Total Number of Instances                8992     
    Ignored Class Unknown Instances          2604

    DOgain does not have any valid values to work with

    Turb = -7.15 * pH + 60.23
    Predicting 0.4 if attribute value is missing.
    Correlation coefficient                  0.2695
    Mean absolute error                      6.1908
    Root mean squared error                  15.8167
    Relative absolute error                  80.0037 %
    Root relative squared error              96.296  %
    Total Number of Instances                11581
    Ignored Class Unknown Instances          15

    Depth Not sure what the point of this would be? depth should be indpendent of everything else. in theory
*/
$drift_variables = [
    "temp"=> [
        "coeff"=>0.13,
        "x"=>"domgl",
        "yi"=>6.69,
        "miss"=>6.89,
        "mae"=>0.3198
    ],
    "ph"=> [
        "coeff"=>-0.08,
        "x"=>"temp",
        "yi"=>9,
        "miss"=>4.93,
        "mae"=>0.3295
    ],
    "phmv"=> [
        "coeff"=>-3.28,
        "x"=>"temp",
        "yi"=>30.73,
        "miss"=>-68.55,
        "mae"=>22.5244
    ],
    "cond"=> [
        "coeff"=>0.01,
        "x"=>"domgl",
        "yi"=>0.7,
        "miss"=>1.03,
        "mae"=>0.1408
    ],
    "dopct" => [
        "coeff"=>28.54,
        "x"=>"ph",
        "yi"=>-150.64,
        "miss"=>92,
        "mae"=>16.6455
    ],
    "domgl"=> [
        "coeff"=>-0.41,
        "x"=>"temp",
        "yi"=>13.85,
        "miss"=>6.8,
        "mae"=>1.6658
    ],
    "dogain"=> [
        "coeff"=>NULL,
        "x"=>NULL,
        "yi"=>NULL,
        "miss"=>NULL,
        "mae"=>NULL
    ],
    "turb"=> [
        "coeff"=>-7.15,
        "x"=>"ph",
        "yi"=>60.23,
        "miss"=>0.4,
        "mae"=>6.1908
    ],
    "depth"=> [
        "coeff"=>NULL,
        "x"=>NULL,
        "yi"=>NULL,
        "miss"=>NULL,
        "mae"=>NULL
    ]    
];
?>