<?php
#equations generated by WEKA machine learning linear regression classifier to detect drift
/*
    Linear regression on Temp
    DOpct = 9.3 * Temp - 150.09
    Predicting 87.52 if attribute value is missing.
    Correlation coefficient                 0.1249
    Mean absolute error                     56.178 
    Root mean squared error                 103.5404
    Relative absolute error                 99.1087 %
    Root relative squared error             99.2036 %
    Total Number of Instances               6411     
    Ignored Class Unknown Instances         478     
*/
$dopct_coefficient = 9.3;
$dopct_x = "temp";
$dopct_yintercept = -150.09;
$dopct_missingx = 87.52;
$dopct_mae = 56.178;
$drift_variables = array(
    "dopct" => array(
        "coeff"=>$dopct_coefficient,
        "x"=>$dopct_x,
        "yi"=>$dopct_yintercept,
        "miss"=>$dopct_missingx,
        "mae"=>$dopct_mae
    )
);
?>